replicaCount: 1

image:
  repository: eadacr5320.azurecr.io/frontend
  tag: ""                                     
  pullPolicy: IfNotPresent

containerPort: 3000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false          
  className: "nginx"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []                   

env:                       
  - name: NODE_ENV
    value: production

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
