apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: app
  labels:
    app.kubernetes.io/name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: user
          # Image will be updated by the deploy-backend workflow
          image: eadacr5320.azurecr.io/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8081"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: MONGO_URI
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: app
  labels:
    app.kubernetes.io/name: user-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: user-service
