replicaCount: 1

image:
  repository: eadacr5320.azurecr.io/frontend   # hardcode ACR repo here
  tag: ""                                       # tag will be set from the workflow
  pullPolicy: IfNotPresent

containerPort: 3000

service:
  type: ClusterIP
  port: 80

env:
  - name: NODE_ENV
    value: production
