name: Deploy Backend

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service to deploy (recipe or user)"
        required: true
        type: string
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        type: string

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group ead-rg \
            --name ead-aks \
            --overwrite-existing

      - name: Create/Update MongoDB secret
        run: |
          kubectl -n app create secret generic mongo \
            --from-literal=MONGO_URI='${{ secrets.MONGO_URI }}' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Set image for the backend
        run: |
          kubectl -n app set image deploy/${{ github.event.inputs.service }}-service \
            ${{ github.event.inputs.service }}=eadacr5320.azurecr.io/${{ github.event.inputs.service }}-service:${{ github.event.inputs.image_tag }}

      - name: Rollout status
        run: |
          kubectl -n app rollout status deploy/${{ github.event.inputs.service }}-service
